name: Build docker image

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      # tag the image with a version when adding a git tag that starts with 'v'
      - name: Build and push tagged image
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/nibiruchain/pricefeeder:${{ steps.get_version.outputs.version-without-v }}

      # tag the image with :latest when pushing to master
      - name: Build and push latest image
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/nibiruchain/pricefeeder:latest
